"""add campaigns table

Revision ID: c3d4e5f6a7b8
Revises: j6k7l8m9n0o1
Create Date: 2026-06-02 18:15:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3d4e5f6a7b8"
down_revision: Union[str, None] = "j6k7l8m9n0o1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("campaign_type", sa.String(length=50), nullable=False),
        sa.Column("discount_type", sa.String(length=30), nullable=False),
        sa.Column("discount_value", sa.Float(), nullable=False),
        sa.Column("max_discount", sa.Float(), nullable=True),
        sa.Column("min_order_value", sa.Float(), nullable=False),
        sa.Column("voucher_code", sa.String(length=50), nullable=True),
        sa.Column("auto_generate_vouchers", sa.Boolean(), nullable=False),
        sa.Column("max_vouchers", sa.Integer(), nullable=True),
        sa.Column("used_vouchers", sa.Integer(), nullable=False),
        sa.Column("target_audience", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("budget", sa.Float(), nullable=True),
        sa.Column("spent", sa.Float(), nullable=False),
        sa.Column("total_orders", sa.Integer(), nullable=False),
        sa.Column("total_revenue", sa.Float(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaigns_campaign_type"), "campaigns", ["campaign_type"], unique=False
    )
    op.create_index(
        op.f("ix_campaigns_end_date"), "campaigns", ["end_date"], unique=False
    )
    op.create_index(
        op.f("ix_campaigns_start_date"), "campaigns", ["start_date"], unique=False
    )
    op.create_index(op.f("ix_campaigns_status"), "campaigns", ["status"], unique=False)
    op.create_index(
        op.f("ix_campaigns_voucher_code"), "campaigns", ["voucher_code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campaigns_voucher_code"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_status"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_start_date"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_end_date"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_campaign_type"), table_name="campaigns")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
